# This is a config for E2B sandbox template.
# You can use template ID (et79grewc9bud6jcsymr) or template name (vibe-nextjs-lucasdev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-lucasdev") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-lucasdev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-lucasdev')

team_id = "ca09532b-54e0-4ee6-bd67-54c24b554ea0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-lucasdev"
template_id = "et79grewc9bud6jcsymr"
